openapi: 3.0.0
info:
  title: Product API
  version: 1.0.0
  description: API for product management
servers:
  - url: http://localhost:3000/api
tags:
  - name: Products
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT